/* Author: lily.tian
 * Project Euler: Problem 2
 * Even Fibonacci Numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms.
 */

public class Problem2 {
	public static void main(String[] args) {

		// stores the sum thus far; starts with 2
		int sum = 2;

		// initiates two fibonacci and the third
		int i = 1;
		int j = 2;
		int k = 0;

		// adds all multiples of 3
		while (k <= 4000000) {
			k = i + j;
			if (k % 2 == 0)
				sum += k;
			i = j;
			j = k;
		}

		// prints answer
		System.out.println(sum);
	}
}