/* Author: lily.tian
 * Project Euler: Problem 012
 * Highly divisible triangular number
 *
 * The sequence of triangle numbers is generated by adding
 * the natural numbers. So the 7th triangle number would be
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 *
 * The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five
 * divisors.
 *
 * What is the value of the first triangle number to have over five
 * hundred divisors?
 */

public class Problem012 {
	public static void main(String[] args) throws Exception {

		// initializes triangular number and divisor
		int tri = 0;
		int div = 0;
		int n = 500;

		for (int i = 1; div <= n; i++){
			tri += i;
			div = 0;
			int factor = 1;
			for (int j = 1; j < tri/factor; j++){
				if (tri % j == 0){
					factor = j;
					div += 2;
				}
			}
		}
		
		// prints answer
		System.out.println(tri);
	}
}